import PDFDocument from "pdfkit";

export interface GenericDocField {
  label: string;
  value: string;
}

export interface GenericDocumentPdfInput {
  title: string; // e.g. "Request for Information"
  documentNumber: string;
  companyName: string;
  companyAddress?: string | null;
  companyPhone?: string | null;
  clientName?: string | null;
  projectName?: string | null;
  createdAt: string | Date;
  fields: GenericDocField[];
  notes?: string | null;
}

const PRIMARY: [number, number, number] = [212, 175, 55];
const DARK: [number, number, number] = [18, 18, 18];
const GRAY: [number, number, number] = [100, 100, 100];
const WHITE: [number, number, number] = [255, 255, 255];
const ACCENT_BROWN: [number, number, number] = [40, 30, 10];
const FOOTER_GRAY: [number, number, number] = [180, 180, 180];

/**
 * Default branded PDF fallback for document types that never had a bespoke
 * PDF builder (RFIs, Proposals, Change Orders — unlike quotes/invoices, see
 * quotePdf.ts/invoicePdf.ts). Same visual language (gold header band, dark
 * footer) so custom-template tenants and default-theme tenants get a
 * consistent look across all five document types.
 */
export function buildGenericDocumentPdfBuffer(input: GenericDocumentPdfInput): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ size: "LETTER", margin: 50 });
    const chunks: Buffer[] = [];
    doc.on("data", (chunk) => chunks.push(chunk));
    doc.on("end", () => resolve(Buffer.concat(chunks)));
    doc.on("error", reject);

    const pageH = doc.page.height;
    const BOTTOM_MARGIN = 60;

    function drawFooter() {
      doc.fillColor(DARK).rect(0, pageH - 30, doc.page.width, 30).fill(DARK);
      doc.fillColor(FOOTER_GRAY).fontSize(8).font("Helvetica");
      doc.text(`Generated by Site Snap · ${input.documentNumber}`, 50, pageH - 14);
      doc.text(
        new Date().toLocaleDateString("en-CA", { year: "numeric", month: "short", day: "numeric" }),
        doc.page.width - 50,
        pageH - 14,
        { align: "right" },
      );
    }

    doc.rect(0, 0, doc.page.width, 80).fill(PRIMARY);
    doc.fillColor(WHITE).fontSize(22).font("Helvetica-Bold");
    doc.text(input.companyName, 50, 28);
    doc.fontSize(10).font("Helvetica").fillColor(ACCENT_BROWN);
    doc.text(input.title.toUpperCase(), doc.page.width - 50, 28, { align: "right" });
    doc.fontSize(14).font("Helvetica-Bold").fillColor(WHITE);
    doc.text(input.documentNumber, doc.page.width - 50, 48, { align: "right" });

    let y = 100;
    function ensureSpace(needed: number) {
      if (y + needed > pageH - BOTTOM_MARGIN) {
        drawFooter();
        doc.addPage();
        y = 50;
      }
    }

    if (input.projectName) {
      doc.fillColor(GRAY).fontSize(8).font("Helvetica-Bold");
      doc.text("PROJECT", 50, y);
      doc.fillColor(DARK).fontSize(12).font("Helvetica-Bold");
      doc.text(input.projectName, 50, y + 14);
      y += 40;
    }
    if (input.clientName) {
      doc.fillColor(GRAY).fontSize(8).font("Helvetica-Bold");
      doc.text("CLIENT", 50, y);
      doc.fillColor(DARK).fontSize(11).font("Helvetica");
      doc.text(input.clientName, 50, y + 14);
      y += 34;
    }

    const dateStr = new Date(input.createdAt).toLocaleDateString("en-CA", {
      year: "numeric",
      month: "short",
      day: "numeric",
    });
    doc.fillColor(GRAY).fontSize(8).font("Helvetica-Bold");
    doc.text("DATE", doc.page.width - 170, 100, { align: "right", width: 120 });
    doc.fillColor(DARK).fontSize(10).font("Helvetica");
    doc.text(dateStr, doc.page.width - 170, 114, { align: "right", width: 120 });

    y += 16;
    doc.moveTo(50, y).lineTo(doc.page.width - 50, y).strokeColor([220, 220, 220]).stroke();
    y += 20;

    for (const field of input.fields) {
      ensureSpace(40);
      doc.fillColor(GRAY).fontSize(8).font("Helvetica-Bold");
      doc.text(field.label.toUpperCase(), 50, y);
      doc.fillColor(DARK).fontSize(10).font("Helvetica");
      const height = doc.heightOfString(field.value, { width: doc.page.width - 100 });
      doc.text(field.value, 50, y + 13, { width: doc.page.width - 100 });
      y += 13 + height + 16;
    }

    if (input.notes) {
      ensureSpace(60);
      doc.fillColor(GRAY).fontSize(8).font("Helvetica-Bold");
      doc.text("NOTES", 50, y);
      y += 14;
      doc.fillColor(DARK).fontSize(9).font("Helvetica");
      doc.text(input.notes, 50, y, { width: doc.page.width - 100 });
      y += doc.heightOfString(input.notes, { width: doc.page.width - 100 }) + 16;
    }

    drawFooter();
    doc.end();
  });
}
