import { Router } from "express";
import { requireAuth, requireCompany } from "../lib/auth";
import { GenerateDailyReportAIBody, GenerateCostAnalysisAIBody, GenerateRFIAIBody } from "@workspace/api-zod";

const router = Router();

// ── Daily Report AI Agent ────────────────────────────────────────────────────
// MOCK: Template-driven AI response. Replace with real LLM call in Phase 2.
router.post("/ai/daily-report/generate", requireAuth, requireCompany, async (req, res) => {
  const parsed = GenerateDailyReportAIBody.safeParse(req.body);
  if (!parsed.success) {
    res.status(400).json({ error: "Invalid body" });
    return;
  }

  const { projectName, rawInput, reportDate, crewCount } = parsed.data;

  // MOCK: Structured extraction from raw notes
  const workPerformed = rawInput.length > 200
    ? rawInput.slice(0, 200) + "..."
    : rawInput;

  res.json({
    workPerformed,
    materialsUsed: extractSection(rawInput, ["material", "concrete", "lumber", "steel", "pipe", "wire"]),
    equipment: extractSection(rawInput, ["excavator", "crane", "loader", "truck", "drill", "saw", "compactor"]),
    issues: extractSection(rawInput, ["issue", "delay", "problem", "concern", "missing", "broken", "safety"]),
    summary: `Daily site report for ${projectName} — ${reportDate}. ` +
      `Crew of ${crewCount ?? "N/A"} performed the following work: ${workPerformed.slice(0, 150)}. ` +
      `Report generated by Construction AI Assistant.`,
  });
});

// ── Cost Analysis AI Agent ───────────────────────────────────────────────────
// MOCK: Template-driven analysis. Replace with real LLM call in Phase 2.
router.post("/ai/cost-analysis/generate", requireAuth, requireCompany, async (req, res) => {
  const parsed = GenerateCostAnalysisAIBody.safeParse(req.body);
  if (!parsed.success) {
    res.status(400).json({ error: "Invalid body" });
    return;
  }

  const { projectName, labourCost, materialsCost, equipmentCost, otherCost, budget } = parsed.data;
  const total = labourCost + materialsCost + equipmentCost + otherCost;
  const labourPct = Math.round((labourCost / total) * 100);
  const matPct = Math.round((materialsCost / total) * 100);
  const budgetUsed = budget ? Math.round((total / budget) * 100) : null;

  const riskLevel: "low" | "medium" | "high" =
    budgetUsed === null ? "low"
    : budgetUsed > 90 ? "high"
    : budgetUsed > 70 ? "medium"
    : "low";

  const recommendations: string[] = [];
  if (labourPct > 50) recommendations.push("Labour costs exceed 50% of total spend — review crew productivity and overtime.");
  if (matPct > 40) recommendations.push("Materials costs are high — consider bulk purchasing or supplier renegotiation.");
  if (budgetUsed && budgetUsed > 80) recommendations.push("Project is approaching budget limit. Review remaining scope carefully.");
  if (recommendations.length === 0) recommendations.push("Costs are within expected ranges. Continue monitoring weekly.");

  res.json({
    analysis: `Cost analysis for ${projectName}. Total expenditure: $${total.toLocaleString("en-CA")} CAD. ` +
      `Labour: ${labourPct}%, Materials: ${matPct}%, Equipment: ${Math.round((equipmentCost / total) * 100)}%, Other: ${Math.round((otherCost / total) * 100)}%.` +
      (budgetUsed ? ` Budget utilization: ${budgetUsed}%.` : ""),
    recommendations,
    riskLevel,
    keyInsights: [
      `Total spend to date: $${total.toLocaleString("en-CA")} CAD`,
      `Largest cost category: ${labourCost >= materialsCost && labourCost >= equipmentCost ? "Labour" : materialsCost >= equipmentCost ? "Materials" : "Equipment"}`,
      budgetUsed ? `Budget utilization: ${budgetUsed}%` : "No budget set for this project",
    ],
  });
});

// ── RFI AI Agent ─────────────────────────────────────────────────────────────
// MOCK: Template-driven RFI generator. Replace with real LLM call in Phase 2.
router.post("/ai/rfi/generate", requireAuth, requireCompany, async (req, res) => {
  const parsed = GenerateRFIAIBody.safeParse(req.body);
  if (!parsed.success) {
    res.status(400).json({ error: "Invalid body" });
    return;
  }

  const { projectName, subject, description } = parsed.data;

  res.json({
    formalSubject: `RFI: ${subject}`,
    formalDescription:
      `PROJECT: ${projectName}\n\n` +
      `SUBJECT: ${subject}\n\n` +
      `DESCRIPTION:\n${description}\n\n` +
      `This Request for Information is submitted to obtain clarification on the above matter. ` +
      `Please provide a response at your earliest convenience to avoid impact to the project schedule.`,
    suggestedResponse:
      `Thank you for submitting this RFI regarding "${subject}". ` +
      `We have reviewed the details and will provide a formal response within 5 business days. ` +
      `Please contact the project manager if this matter is time-sensitive.`,
    clarifyingQuestions: [
      "What is the impact on the project schedule if this is not resolved within 5 business days?",
      "Are there any related drawings or specifications that should be reviewed?",
      "Has this issue been discussed verbally with the site supervisor?",
    ],
  });
});

// Helper: extract sentences from raw text that contain keywords
function extractSection(text: string, keywords: string[]): string {
  const sentences = text.split(/[.!?]\s+/);
  const relevant = sentences.filter((s) =>
    keywords.some((k) => s.toLowerCase().includes(k)),
  );
  return relevant.length > 0 ? relevant.join(". ") : "";
}

export default router;
