import { Router, type IRouter } from "express";
import healthRouter from "./health";
import usersRouter from "./users";
import companiesRouter from "./companies";
import invitationsRouter from "./invitations";
import projectsRouter from "./projects";
import dailyReportsRouter from "./dailyReports";
import costAnalysesRouter from "./costAnalyses";
import rfisRouter from "./rfis";
import aiRouter from "./ai";
import conversationsRouter from "./conversations";
import dashboardRouter from "./dashboard";
import tasksRouter from "./tasks";
import photosRouter from "./photos";
import storageRouter from "./storage";
import notificationsRouter from "./notifications";
import digestRouter from "./digest";
import documentsRouter from "./documents";
import quotesRouter from "./quotes";
import invoicesRouter from "./invoices";
import billingRouter from "./billing";
import referralsRouter from "./referrals";
import quickbooksRouter from "./quickbooks";
import scheduleRouter from "./schedule";
import portalRouter from "./portal";
import timeEntriesRouter from "./timeEntries";
import companyTimeEntriesRouter from "./companyTimeEntries";
import estimatesRouter from "./estimates";
import timesheetsRouter from "./timesheets";
import superAdminRouter from "./superAdmin";
import safetyRouter from "./safety";
import tradehubRouter from "./tradehub";
import calculatorsRouter from "./calculators";
import contactsRouter from "./contacts";

const router: IRouter = Router();

router.use(healthRouter);
router.use(usersRouter);
router.use(companiesRouter);
router.use(invitationsRouter);
router.use(projectsRouter);
router.use("/projects/:projectId/daily-reports", dailyReportsRouter);
router.use("/projects/:projectId/cost-analyses", costAnalysesRouter);
router.use("/projects/:projectId/rfis", rfisRouter);
router.use("/projects/:projectId/tasks", tasksRouter);
router.use("/projects/:projectId/daily-reports/:reportId/photos", photosRouter);
router.use("/projects/:projectId/documents", documentsRouter);
router.use("/projects/:projectId/quotes", quotesRouter);
router.use(invoicesRouter);
router.use(aiRouter);
router.use(conversationsRouter);
router.use(dashboardRouter);
router.use(storageRouter);
router.use(notificationsRouter);
router.use(digestRouter);
router.use(billingRouter);
router.use(referralsRouter);
router.use(quickbooksRouter);
router.use(scheduleRouter);
router.use(portalRouter);
router.use("/projects/:projectId/time-entries", timeEntriesRouter);
router.use(companyTimeEntriesRouter);
router.use(estimatesRouter);
router.use(timesheetsRouter);
router.use(superAdminRouter);
router.use(safetyRouter);
router.use(tradehubRouter);
router.use(calculatorsRouter);
router.use(contactsRouter);

export default router;
