import { Router, type IRouter } from "express";
import healthRouter from "./health";
import usersRouter from "./users";
import companiesRouter from "./companies";
import invitationsRouter from "./invitations";
import projectsRouter from "./projects";
import dailyReportsRouter, { allDailyReportsRouter } from "./dailyReports";
import costAnalysesRouter from "./costAnalyses";
import rfisRouter, { allRfisRouter } from "./rfis";
import aiRouter from "./ai";
import conversationsRouter from "./conversations";
import dashboardRouter from "./dashboard";
import tasksRouter from "./tasks";
import photosRouter from "./photos";
import storageRouter from "./storage";
import notificationsRouter from "./notifications";
import digestRouter from "./digest";
import documentsRouter from "./documents";
import quotesRouter from "./quotes";
import invoicesRouter from "./invoices";
import billingRouter from "./billing";
import referralsRouter from "./referrals";
import quickbooksRouter from "./quickbooks";
import scheduleRouter from "./schedule";
import portalRouter from "./portal";
import timeEntriesRouter from "./timeEntries";
import companyTimeEntriesRouter from "./companyTimeEntries";
import estimatesRouter from "./estimates";
import timesheetsRouter from "./timesheets";
import superAdminRouter from "./superAdmin";
import safetyRouter from "./safety";
import tradehubRouter from "./tradehub";
import calculatorsRouter from "./calculators";
import contactsRouter from "./contacts";
import leadsRouter from "./leads";
import proposalsRouter from "./proposals";
import accountingRouter from "./accounting";
import financialsRouter from "./financials";
import formsRouter from "./forms";
import filesRouter from "./files";
import estimatorRouter from "./estimator";
import photoSummaryRouter from "./photoSummary";
import inspectionsRouter from "./inspections";
import riskDashboardRouter from "./riskDashboard";
import scheduleEventsRouter from "./scheduleEvents";
import publicRouter from "./public";
import scansRouter from "./scans";
import fieldAutomationRouter from "./fieldAutomation";
import productivityIntegrationsRouter from "./integrations/productivity";
import mediaHubRouter from "./mediaHub";
import workerVaultRouter from "./workerVault";
import tradeReviewsRouter from "./tradeReviews";
import auditLogsRouter from "./auditLogs";

const router: IRouter = Router();

// Public (unauthenticated) routes — must be mounted BEFORE any auth middleware.
router.use(publicRouter);

router.use(healthRouter);
router.use(usersRouter);
router.use(companiesRouter);
router.use(invitationsRouter);
router.use(projectsRouter);
router.use(allDailyReportsRouter);
router.use(allRfisRouter);
router.use("/projects/:projectId/daily-reports", dailyReportsRouter);
router.use("/projects/:projectId/cost-analyses", costAnalysesRouter);
router.use("/projects/:projectId/rfis", rfisRouter);
router.use("/projects/:projectId/tasks", tasksRouter);
router.use("/projects/:projectId/daily-reports/:reportId/photos", photosRouter);
router.use("/projects/:projectId/documents", documentsRouter);
router.use("/projects/:projectId/quotes", quotesRouter);
router.use(invoicesRouter);
router.use(aiRouter);
router.use(conversationsRouter);
router.use(dashboardRouter);
router.use(storageRouter);
router.use(notificationsRouter);
router.use(digestRouter);
router.use(billingRouter);
router.use(referralsRouter);
router.use(quickbooksRouter);
router.use(scheduleRouter);
router.use(portalRouter);
router.use("/projects/:projectId/time-entries", timeEntriesRouter);
router.use(companyTimeEntriesRouter);
router.use(estimatesRouter);
router.use(timesheetsRouter);
router.use(superAdminRouter);
router.use(safetyRouter);
router.use(tradehubRouter);
router.use(calculatorsRouter);
router.use(contactsRouter);
router.use(leadsRouter);
router.use(proposalsRouter);
router.use(accountingRouter);
router.use(financialsRouter);
router.use(formsRouter);
router.use(filesRouter);
router.use(estimatorRouter);
router.use(photoSummaryRouter);
router.use(inspectionsRouter);
router.use(riskDashboardRouter);
router.use(scheduleEventsRouter);
router.use(scansRouter);
router.use(fieldAutomationRouter);
router.use(productivityIntegrationsRouter);
router.use(mediaHubRouter);
router.use(workerVaultRouter);
router.use(tradeReviewsRouter);
router.use(auditLogsRouter);

export default router;
