// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/black-gold/DataTable.tsx": () => import("../components/mockups/black-gold/DataTable.tsx"),
  "./components/mockups/black-gold/DataTableV2.tsx": () => import("../components/mockups/black-gold/DataTableV2.tsx"),
  "./components/mockups/black-gold/DataTableV3.tsx": () => import("../components/mockups/black-gold/DataTableV3.tsx"),
  "./components/mockups/black-gold/DataTableV4.tsx": () => import("../components/mockups/black-gold/DataTableV4.tsx"),
  "./components/mockups/black-gold/Sidebar.tsx": () => import("../components/mockups/black-gold/Sidebar.tsx"),
  "./components/mockups/themes/ThemeA.tsx": () => import("../components/mockups/themes/ThemeA.tsx"),
  "./components/mockups/themes/ThemeB.tsx": () => import("../components/mockups/themes/ThemeB.tsx"),
  "./components/mockups/themes/ThemeC.tsx": () => import("../components/mockups/themes/ThemeC.tsx"),
  "./components/mockups/schemes/SchemeA.tsx": () => import("../components/mockups/schemes/SchemeA.tsx"),
  "./components/mockups/schemes/SchemeB.tsx": () => import("../components/mockups/schemes/SchemeB.tsx"),
  "./components/mockups/schemes/SchemeC.tsx": () => import("../components/mockups/schemes/SchemeC.tsx")
};
