#!/usr/bin/env bash
# Validates that lib/api-zod/src/index.ts has not been manually edited.
# Allowed content:
#   Line 1: // AUTOGENERATED - DO NOT EDIT. Run pnpm codegen instead.
#   Line 2: // export * from "./generated/api"; must remain the only export.
#   Line 3: (optional blank line)
#   Final non-blank line: export * from "./generated/api";

set -euo pipefail

FILE="lib/api-zod/src/index.ts"

if [ ! -f "$FILE" ]; then
  echo "ERROR: $FILE not found." >&2
  exit 1
fi

# Strip trailing newline and read all lines
mapfile -t lines < "$FILE"

EXPECTED_LINE1='// AUTOGENERATED - DO NOT EDIT. Run pnpm codegen instead.'
EXPECTED_LINE2='// export * from "./generated/api"; must remain the only export.'
EXPECTED_EXPORT='export * from "./generated/api";'

# Filter out blank lines to get only meaningful content lines
meaningful=()
for line in "${lines[@]}"; do
  if [[ -n "${line// /}" ]]; then
    meaningful+=("$line")
  fi
done

# Must have exactly 3 meaningful lines: 2 comment lines + 1 export line
if [ "${#meaningful[@]}" -ne 3 ]; then
  echo "ERROR: $FILE contains unexpected content." >&2
  echo "  Expected exactly 3 non-blank lines (2 comment header lines + 1 export statement)." >&2
  echo "  Found ${#meaningful[@]} non-blank line(s)." >&2
  echo "  Do not manually edit this file — run 'pnpm codegen' instead." >&2
  exit 1
fi

if [ "${meaningful[0]}" != "$EXPECTED_LINE1" ]; then
  echo "ERROR: $FILE line 1 does not match the required comment header." >&2
  echo "  Expected: $EXPECTED_LINE1" >&2
  echo "  Found:    ${meaningful[0]}" >&2
  echo "  Do not manually edit this file — run 'pnpm codegen' instead." >&2
  exit 1
fi

if [ "${meaningful[1]}" != "$EXPECTED_LINE2" ]; then
  echo "ERROR: $FILE line 2 does not match the required comment header." >&2
  echo "  Expected: $EXPECTED_LINE2" >&2
  echo "  Found:    ${meaningful[1]}" >&2
  echo "  Do not manually edit this file — run 'pnpm codegen' instead." >&2
  exit 1
fi

if [ "${meaningful[2]}" != "$EXPECTED_EXPORT" ]; then
  echo "ERROR: $FILE contains an invalid or extra export statement." >&2
  echo "  Expected: $EXPECTED_EXPORT" >&2
  echo "  Found:    ${meaningful[2]}" >&2
  echo "  Only 'export * from \"./generated/api\";' is allowed." >&2
  echo "  Do not manually edit this file — run 'pnpm codegen' instead." >&2
  exit 1
fi

echo "OK: $FILE is valid."
exit 0
