import { useParams, useSearch } from "wouter";
import {
  Document,
  Page,
  Text,
  View,
  PDFViewer,
  PDFDownloadLink,
} from "@react-pdf/renderer";
import {
  useGetProject,
  useGetProjectSummary,
  useListDailyReports,
  useListCostAnalyses,
  useListRFIs,
  useListTasks,
  useListCompanyMembers,
  useGetMe,
  getListChangeOrdersQueryOptions,
  customFetch,
} from "@workspace/api-client-react";
import type {
  Project,
  ProjectSummary,
  DailyReport,
  Task,
  Rfi,
  CostAnalysis,
  ChangeOrderRecord,
  UserWithCompany,
  FormSubmissionRecord,
} from "@workspace/api-client-react";
import { useQuery } from "@tanstack/react-query";
import { format } from "date-fns";

import { styles, COLORS, SIZES } from "@/components/pdf/theme";
import ProjectInfoSection from "@/components/pdf/ProjectInfoSection";
import NotesSection from "@/components/pdf/NotesSection";
import DailyReportsSection from "@/components/pdf/DailyReportsSection";
import TasksSection from "@/components/pdf/TasksSection";
import RFIsSection from "@/components/pdf/RFIsSection";
import ScheduleSection from "@/components/pdf/ScheduleSection";
import CostSummarySection from "@/components/pdf/CostSummarySection";
import ChangeOrdersSection from "@/components/pdf/ChangeOrdersSection";
import SafetySection from "@/components/pdf/SafetySection";

interface ProjectNote {
  id: number;
  content: string;
  createdAt: string;
  author?: {
    id: number;
    firstName: string;
    lastName: string;
  } | null;
}

interface ScheduleAssignment {
  id: number;
  userFirstName?: string | null;
  userLastName?: string | null;
  userRole?: string | null;
  startDate: string;
  endDate: string;
  notes?: string | null;
}

function PDFHeader({ projectName }: { projectName: string }) {
  return (
    <View style={styles.header} fixed>
      <Text style={styles.headerTitle}>Site Snap</Text>
      <Text style={styles.headerSubtitle}>
        Project Report — {projectName}
      </Text>
    </View>
  );
}

function PDFFooter() {
  return (
    <View style={styles.footer} fixed>
      <Text>Generated by Site Snap on {format(new Date(), "MMM d, yyyy")}</Text>
      <Text
        render={({ pageNumber, totalPages }) => `Page ${pageNumber} of ${totalPages}`}
      />
    </View>
  );
}

interface PDFDocumentProps {
  project: Project;
  summary: ProjectSummary | undefined;
  notes: ProjectNote[];
  reports: DailyReport[];
  tasks: Task[];
  members: UserWithCompany[];
  rfis: Rfi[];
  assignments: ScheduleAssignment[];
  costAnalyses: CostAnalysis[];
  changeOrders: ChangeOrderRecord[];
  safetySubmissions: FormSubmissionRecord[];
  sections: Record<string, boolean>;
}

function PDFDocument({
  project,
  summary,
  notes,
  reports,
  tasks,
  members,
  rfis,
  assignments,
  costAnalyses,
  changeOrders,
  safetySubmissions,
  sections,
}: PDFDocumentProps) {
  return (
    <Document>
      {/* Project Info — always included */}
      <Page size="A4" style={styles.page}>
        <PDFHeader projectName={project.name} />
        <ProjectInfoSection project={project} summary={summary} />
        <PDFFooter />
      </Page>

      {/* Notes */}
      {sections.notes && (
        <Page size="A4" style={styles.page}>
          <PDFHeader projectName={project.name} />
          <NotesSection notes={notes} />
          <PDFFooter />
        </Page>
      )}

      {/* Daily Reports */}
      {sections.reports && (
        <Page size="A4" style={styles.page}>
          <PDFHeader projectName={project.name} />
          <DailyReportsSection reports={reports} />
          <PDFFooter />
        </Page>
      )}

      {/* Tasks */}
      {sections.tasks && (
        <Page size="A4" style={styles.page}>
          <PDFHeader projectName={project.name} />
          <TasksSection tasks={tasks} members={members} />
          <PDFFooter />
        </Page>
      )}

      {/* RFIs */}
      {sections.rfis && (
        <Page size="A4" style={styles.page}>
          <PDFHeader projectName={project.name} />
          <RFIsSection rfis={rfis} />
          <PDFFooter />
        </Page>
      )}

      {/* Schedule */}
      {sections.schedule && (
        <Page size="A4" style={styles.page}>
          <PDFHeader projectName={project.name} />
          <ScheduleSection assignments={assignments} />
          <PDFFooter />
        </Page>
      )}

      {/* Cost Analysis */}
      {sections.cost && (
        <Page size="A4" style={styles.page}>
          <PDFHeader projectName={project.name} />
          <CostSummarySection costAnalyses={costAnalyses} />
          <PDFFooter />
        </Page>
      )}

      {/* Change Orders */}
      {sections.changeOrders && (
        <Page size="A4" style={styles.page}>
          <PDFHeader projectName={project.name} />
          <ChangeOrdersSection changeOrders={changeOrders} />
          <PDFFooter />
        </Page>
      )}

      {/* Safety */}
      {sections.safety && (
        <Page size="A4" style={styles.page}>
          <PDFHeader projectName={project.name} />
          <SafetySection submissions={safetySubmissions} />
          <PDFFooter />
        </Page>
      )}
    </Document>
  );
}

export default function ProjectPrintPage() {
  const params = useParams();
  const projectId = Number(params.id);
  const search = useSearch();

  const paramsObj = new URLSearchParams(search);
  const sections: Record<string, boolean> = {
    info: paramsObj.get("info") !== "false",
    notes: paramsObj.get("notes") === "true",
    reports: paramsObj.get("reports") === "true",
    tasks: paramsObj.get("tasks") === "true",
    rfis: paramsObj.get("rfis") === "true",
    schedule: paramsObj.get("schedule") === "true",
    cost: paramsObj.get("cost") === "true",
    changeOrders: paramsObj.get("changeOrders") === "true",
    safety: paramsObj.get("safety") === "true",
  };

  const { data: me } = useGetMe();
  const companyId = me?.company?.id;

  const { data: project } = useGetProject(projectId);
  const { data: summary } = useGetProjectSummary(projectId);
  const { data: reports } = useListDailyReports(projectId);
  const { data: costAnalyses } = useListCostAnalyses(projectId);
  const { data: rfis } = useListRFIs(projectId);
  const { data: allTasks = [] } = useListTasks(projectId);
  const { data: members = [] } = useListCompanyMembers(companyId ?? 0);

  const { data: notes = [] } = useQuery<ProjectNote[]>({
    queryKey: ["project-notes", projectId],
    queryFn: () => customFetch(`/api/projects/${projectId}/notes`),
    enabled: sections.notes,
  });

  const { data: assignments = [] } = useQuery<ScheduleAssignment[]>({
    queryKey: ["project-schedule", projectId],
    queryFn: () => customFetch(`/api/projects/${projectId}/schedule`),
    enabled: sections.schedule,
  });

  const { data: changeOrders = [] } = useQuery({
    ...getListChangeOrdersQueryOptions({ projectId }),
    enabled: sections.changeOrders,
  });

  const { data: allSafetySubmissions = [] } = useQuery<FormSubmissionRecord[]>({
    queryKey: ["safety-submissions", projectId],
    queryFn: () => customFetch(`/api/safety/submissions`),
    enabled: sections.safety,
  });
  const safetySubmissions = allSafetySubmissions.filter(
    (s) => s.projectId === projectId
  );

  if (!project) {
    return (
      <div className="flex items-center justify-center h-screen">
        <p className="text-muted-foreground">Loading project...</p>
      </div>
    );
  }

  const enrichedReports = (reports ?? []).map((report) => ({
    ...report,
    photos: (report as DailyReport & { photos?: { id: number; objectPath: string; caption?: string | null }[] }).photos ?? [],
  }));

  const fileName = `${project.name.replace(/[^a-zA-Z0-9]/g, "_")}_Report.pdf`;

  return (
    <div className="h-screen flex flex-col bg-muted/20">
      <div className="bg-white border-b px-4 py-3 flex items-center justify-between shrink-0">
        <div>
          <h1 className="font-bold text-lg">Print Preview</h1>
          <p className="text-sm text-muted-foreground">{project.name}</p>
        </div>
        <PDFDownloadLink
          document={
            <PDFDocument
              project={project}
              summary={summary}
              notes={notes}
              reports={enrichedReports}
              tasks={allTasks}
              members={members}
              rfis={rfis ?? []}
              assignments={assignments}
              costAnalyses={costAnalyses ?? []}
              changeOrders={changeOrders}
              safetySubmissions={safetySubmissions}
              sections={sections}
            />
          }
          fileName={fileName}
          className="inline-flex items-center gap-2 bg-primary text-primary-foreground px-4 py-2 rounded-md text-sm font-medium hover:bg-primary/90 transition-colors"
        >
          {({ loading }) => (loading ? "Generating PDF..." : "Download PDF")}
        </PDFDownloadLink>
      </div>
      <div className="flex-1">
        <PDFViewer width="100%" height="100%" className="border-0">
          <PDFDocument
            project={project}
            summary={summary}
            notes={notes}
            reports={enrichedReports}
            tasks={allTasks}
            members={members}
            rfis={rfis ?? []}
            assignments={assignments}
            costAnalyses={costAnalyses ?? []}
            changeOrders={changeOrders}
            safetySubmissions={safetySubmissions}
            sections={sections}
          />
        </PDFViewer>
      </div>
    </div>
  );
}
