import { useParams, useSearch } from "wouter";
import {
  Document,
  Page,
  Text,
  View,
  PDFViewer,
  PDFDownloadLink,
} from "@react-pdf/renderer";
import {
  useGetProject,
  useGetProjectSummary,
  useListDailyReports,
  useListCostAnalyses,
  useListRFIs,
  useListTasks,
  useListCompanyMembers,
  useGetMe,
  customFetch,
  listChangeOrders,
} from "@workspace/api-client-react";
import { useQuery } from "@tanstack/react-query";
import { format } from "date-fns";

import { styles, COLORS, FONTS, SIZES } from "@/components/pdf/theme";
import ProjectInfoSection from "@/components/pdf/ProjectInfoSection";
import NotesSection from "@/components/pdf/NotesSection";
import DailyReportsSection from "@/components/pdf/DailyReportsSection";
import TasksSection from "@/components/pdf/TasksSection";
import RFIsSection from "@/components/pdf/RFIsSection";
import ScheduleSection from "@/components/pdf/ScheduleSection";
import CostSummarySection from "@/components/pdf/CostSummarySection";
import ChangeOrdersSection from "@/components/pdf/ChangeOrdersSection";
import SafetySection from "@/components/pdf/SafetySection";

function PDFHeader({ projectName }: { projectName: string }) {
  return (
    <View style={styles.header} fixed>
      <Text style={styles.headerTitle}>Site Snap</Text>
      <Text style={styles.headerSubtitle}>
        Project Report — {projectName}
      </Text>
    </View>
  );
}

function PDFFooter() {
  return (
    <View style={styles.footer} fixed>
      <Text>Generated by Site Snap on {format(new Date(), "MMM d, yyyy")}</Text>
      <Text
        render={({ pageNumber, totalPages }) => `Page ${pageNumber} of ${totalPages}`}
      />
    </View>
  );
}

function PDFDocument({
  project,
  summary,
  notes,
  reports,
  tasks,
  members,
  rfis,
  assignments,
  costAnalyses,
  changeOrders,
  safetySubmissions,
  sections,
}: {
  project: any;
  summary: any;
  notes: any[];
  reports: any[];
  tasks: any[];
  members: any[];
  rfis: any[];
  assignments: any[];
  costAnalyses: any[];
  changeOrders: any[];
  safetySubmissions: any[];
  sections: Record<string, boolean>;
}) {
  return (
    <Document>
      <Page size="A4" style={styles.page}>
        <PDFHeader projectName={project.name} />

        {sections.info !== false && (
          <ProjectInfoSection project={project} summary={summary} />
        )}

        {sections.info !== false && (
          <View style={{ marginTop: SIZES.sectionGap }} />
        )}

        {sections.notes && <NotesSection notes={notes} />}
        {sections.notes && <View style={{ marginTop: SIZES.sectionGap }} />}

        {sections.reports && <DailyReportsSection reports={reports} />}
        {sections.reports && <View style={{ marginTop: SIZES.sectionGap }} />}

        {sections.tasks && <TasksSection tasks={tasks} members={members} />}
        {sections.tasks && <View style={{ marginTop: SIZES.sectionGap }} />}

        {sections.rfis && <RFIsSection rfis={rfis} />}
        {sections.rfis && <View style={{ marginTop: SIZES.sectionGap }} />}

        {sections.schedule && <ScheduleSection assignments={assignments} />}
        {sections.schedule && <View style={{ marginTop: SIZES.sectionGap }} />}

        {sections.cost && <CostSummarySection costAnalyses={costAnalyses} />}
        {sections.cost && <View style={{ marginTop: SIZES.sectionGap }} />}

        {sections.changeOrders && <ChangeOrdersSection changeOrders={changeOrders} />}
        {sections.changeOrders && <View style={{ marginTop: SIZES.sectionGap }} />}

        {sections.safety && <SafetySection submissions={safetySubmissions} />}

        <PDFFooter />
      </Page>
    </Document>
  );
}

export default function ProjectPrintPage() {
  const params = useParams();
  const projectId = Number(params.id);
  const search = useSearch();

  const paramsObj = new URLSearchParams(search);
  const sections: Record<string, boolean> = {
    info: paramsObj.get("info") !== "false",
    notes: paramsObj.get("notes") === "true",
    reports: paramsObj.get("reports") === "true",
    tasks: paramsObj.get("tasks") === "true",
    rfis: paramsObj.get("rfis") === "true",
    schedule: paramsObj.get("schedule") === "true",
    cost: paramsObj.get("cost") === "true",
    changeOrders: paramsObj.get("changeOrders") === "true",
    safety: paramsObj.get("safety") === "true",
  };

  const { data: me } = useGetMe();
  const companyId = me?.company?.id;

  const { data: project } = useGetProject(projectId);
  const { data: summary } = useGetProjectSummary(projectId);
  const { data: reports } = useListDailyReports(projectId);
  const { data: costAnalyses } = useListCostAnalyses(projectId);
  const { data: rfis } = useListRFIs(projectId);
  const { data: allTasks = [] } = useListTasks(projectId);
  const { data: members = [] } = useListCompanyMembers(
    companyId ?? 0,
    { query: { enabled: !!companyId } as any }
  );

  const { data: notes = [] } = useQuery({
    queryKey: ["project-notes", projectId],
    queryFn: () => customFetch(`/api/projects/${projectId}/notes`) as Promise<any[]>,
    enabled: sections.notes,
  });

  const { data: assignments = [] } = useQuery({
    queryKey: ["project-schedule", projectId],
    queryFn: () => customFetch(`/api/projects/${projectId}/schedule`) as Promise<any[]>,
    enabled: sections.schedule,
  });

  const { data: changeOrders = [] } = useQuery({
    queryKey: ["change-orders", projectId],
    queryFn: () => listChangeOrders({ projectId }) as Promise<any[]>,
    enabled: sections.changeOrders,
  });

  const { data: allSafetySubmissions = [] } = useQuery({
    queryKey: ["safety-submissions", projectId],
    queryFn: () =>
      customFetch(`/api/safety/submissions`) as Promise<any[]>,
    enabled: sections.safety,
  });
  const safetySubmissions = allSafetySubmissions.filter((s: any) => s.projectId === projectId);

  if (!project) {
    return (
      <div className="flex items-center justify-center h-screen">
        <p className="text-muted-foreground">Loading project...</p>
      </div>
    );
  }

  // Enrich reports with photos
  const enrichedReports = (reports ?? []).map((report: any) => ({
    ...report,
    photos: report.photos ?? [],
  }));

  const fileName = `${project.name.replace(/[^a-zA-Z0-9]/g, "_")}_Report.pdf`;

  return (
    <div className="h-screen flex flex-col bg-muted/20">
      <div className="bg-white border-b px-4 py-3 flex items-center justify-between shrink-0">
        <div>
          <h1 className="font-bold text-lg">Print Preview</h1>
          <p className="text-sm text-muted-foreground">{project.name}</p>
        </div>
        <PDFDownloadLink
          document={
            <PDFDocument
              project={project}
              summary={summary}
              notes={notes}
              reports={enrichedReports}
              tasks={allTasks}
              members={members as any[]}
              rfis={rfis ?? []}
              assignments={assignments}
              costAnalyses={costAnalyses ?? []}
              changeOrders={changeOrders}
              safetySubmissions={safetySubmissions}
              sections={sections}
            />
          }
          fileName={fileName}
          className="inline-flex items-center gap-2 bg-primary text-primary-foreground px-4 py-2 rounded-md text-sm font-medium hover:bg-primary/90 transition-colors"
        >
          {({ loading }) => (loading ? "Generating PDF..." : "Download PDF")}
        </PDFDownloadLink>
      </div>
      <div className="flex-1">
        <PDFViewer width="100%" height="100%" className="border-0">
          <PDFDocument
            project={project}
            summary={summary}
            notes={notes}
            reports={enrichedReports}
            tasks={allTasks}
            members={members as any[]}
            rfis={rfis ?? []}
            assignments={assignments}
            costAnalyses={costAnalyses ?? []}
            changeOrders={changeOrders}
            safetySubmissions={safetySubmissions}
            sections={sections}
          />
        </PDFViewer>
      </div>
    </div>
  );
}
