import { useSearch } from "wouter";
import {
  Document,
  Page,
  Text,
  View,
  PDFViewer,
  pdf,
} from "@react-pdf/renderer";
import {
  customFetch,
  useGetMe,
} from "@workspace/api-client-react";
import type { FormSubmissionRecord } from "@workspace/api-client-react";
import { useQuery } from "@tanstack/react-query";
import { format } from "date-fns";

import { styles, COLORS } from "@/components/pdf/theme";
import SafetySubmissionsSection from "@/components/pdf/SafetySubmissionsSection";

function PDFHeader({ companyName }: { companyName: string }) {
  return (
    <View style={styles.header} fixed>
      <Text style={styles.headerTitle}>Site Snap</Text>
      <Text style={styles.headerSubtitle}>
        Safety & Compliance Report{companyName ? ` \u2014 ${companyName}` : ""}
      </Text>
    </View>
  );
}

function PDFFooter() {
  return (
    <View style={styles.footer} fixed>
      <Text>Generated by Site Snap on {format(new Date(), "MMM d, yyyy")}</Text>
      <Text
        render={({ pageNumber, totalPages }) => `Page ${pageNumber} of ${totalPages}`}
      />
    </View>
  );
}

interface SafetyNotesSectionProps {
  submissions: FormSubmissionRecord[];
}

function SafetyNotesSection({ submissions }: SafetyNotesSectionProps) {
  const withNotes = submissions.filter((s) => s.aiSummary);

  if (withNotes.length === 0) {
    return (
      <View>
        <Text style={styles.sectionTitle}>Safety Notes & AI Summaries</Text>
        <View style={styles.sectionDivider} />
        <Text style={styles.emptyState}>No AI summaries or safety notes available.</Text>
      </View>
    );
  }

  return (
    <View>
      <Text style={styles.sectionTitle}>Safety Notes & AI Summaries</Text>
      <View style={styles.sectionDivider} />
      {withNotes.map((sub) => (
        <View key={sub.id} style={styles.card}>
          <Text style={styles.cardTitle}>{sub.templateName ?? "Safety Form"}</Text>
          <Text style={styles.smallText}>
            {format(new Date(sub.createdAt), "MMM d, yyyy")}
            {sub.workerName ? ` \u2014 ${sub.workerName}` : ""}
          </Text>
          <View style={{ marginTop: 6, backgroundColor: "#f0f9ff", padding: 6, borderRadius: 3 }}>
            <Text style={[styles.smallText, { color: COLORS.blue }]}>{sub.aiSummary}</Text>
          </View>
        </View>
      ))}
    </View>
  );
}

function buildPhotosMap(submissions: FormSubmissionRecord[]): Record<number, { id: number; url: string }[]> {
  const map: Record<number, { id: number; url: string }[]> = {};
  for (const sub of submissions) {
    if (Array.isArray(sub.photos) && sub.photos.length > 0) {
      map[sub.id] = sub.photos.map((p) => ({ id: p.id, url: p.url }));
    }
  }
  return map;
}

interface PDFDocumentProps {
  submissions: FormSubmissionRecord[];
  companyName: string;
  sections: Record<string, boolean>;
}

function PDFDocument({ submissions, companyName, sections }: PDFDocumentProps) {
  const ppeSubmissions = submissions.filter(
    (s) => s.templateCategory === "safety" && /ppe|equipment|gear|hard.?hat|vest|gloves|boots|harness|goggle|mask/i.test(s.templateName ?? "")
  );

  const photosMap = buildPhotosMap(submissions);

  return (
    <Document>
      {/* Overview / Stats */}
      <Page size="A4" style={styles.page}>
        <PDFHeader companyName={companyName} />
        <View>
          <Text style={styles.sectionTitle}>Overview</Text>
          <View style={styles.sectionDivider} />
          <View style={styles.grid2}>
            {[
              { label: "Total Submissions", value: String(submissions.length) },
              { label: "Inspections", value: String(submissions.filter((s) => s.templateCategory === "safety").length) },
              { label: "Hazard Reports", value: String(submissions.filter((s) => s.templateCategory === "hazard").length) },
              { label: "Incidents", value: String(submissions.filter((s) => s.templateCategory === "injury").length) },
              { label: "Toolbox Talks", value: String(submissions.filter((s) => s.templateCategory === "toolbox").length) },
              { label: "PPE Checks", value: String(ppeSubmissions.length) },
            ].map(({ label, value }) => (
              <View key={label} style={[styles.gridItem, styles.card]}>
                <Text style={styles.label}>{label}</Text>
                <Text style={[styles.value, { fontSize: 16, marginTop: 4 }]}>{value}</Text>
              </View>
            ))}
          </View>
        </View>
        <PDFFooter />
      </Page>

      {/* Inspections */}
      {sections.inspections && (
        <Page size="A4" style={styles.page}>
          <PDFHeader companyName={companyName} />
          <SafetySubmissionsSection
            submissions={submissions}
            category="safety"
            title="Inspections"
            photosMap={photosMap}
          />
          <PDFFooter />
        </Page>
      )}

      {/* Hazard Log */}
      {sections.hazard && (
        <Page size="A4" style={styles.page}>
          <PDFHeader companyName={companyName} />
          <SafetySubmissionsSection
            submissions={submissions}
            category="hazard"
            title="Hazard Log"
            photosMap={photosMap}
          />
          <PDFFooter />
        </Page>
      )}

      {/* Incident Reports */}
      {sections.incidents && (
        <Page size="A4" style={styles.page}>
          <PDFHeader companyName={companyName} />
          <SafetySubmissionsSection
            submissions={submissions}
            category="injury"
            title="Incident Reports"
            photosMap={photosMap}
            showSeverity
          />
          <PDFFooter />
        </Page>
      )}

      {/* Toolbox Talks */}
      {sections.toolbox && (
        <Page size="A4" style={styles.page}>
          <PDFHeader companyName={companyName} />
          <SafetySubmissionsSection
            submissions={submissions}
            category="toolbox"
            title="Toolbox Talks"
            photosMap={photosMap}
          />
          <PDFFooter />
        </Page>
      )}

      {/* PPE Compliance */}
      {sections.ppe && (
        <Page size="A4" style={styles.page}>
          <PDFHeader companyName={companyName} />
          <SafetySubmissionsSection
            submissions={ppeSubmissions}
            title="PPE Compliance"
            photosMap={photosMap}
          />
          <PDFFooter />
        </Page>
      )}

      {/* Safety Notes / AI Summaries */}
      {sections.notes && (
        <Page size="A4" style={styles.page}>
          <PDFHeader companyName={companyName} />
          <SafetyNotesSection submissions={submissions} />
          <PDFFooter />
        </Page>
      )}
    </Document>
  );
}

export default function SafetyPrintPage() {
  const search = useSearch();
  const paramsObj = new URLSearchParams(search);

  const sections: Record<string, boolean> = {
    inspections: paramsObj.get("inspections") !== "false",
    hazard: paramsObj.get("hazard") === "true",
    incidents: paramsObj.get("incidents") === "true",
    toolbox: paramsObj.get("toolbox") === "true",
    ppe: paramsObj.get("ppe") === "true",
    notes: paramsObj.get("notes") === "true",
  };

  const { data: me } = useGetMe();
  const companyName = me?.company?.name ?? "";

  const { data: submissions = [], isLoading: subsLoading } = useQuery<FormSubmissionRecord[]>({
    queryKey: ["safety-submissions", "all"],
    queryFn: () => customFetch(`/api/safety/submissions`),
  });

  if (subsLoading) {
    return (
      <div className="flex items-center justify-center h-screen">
        <p className="text-muted-foreground">Loading safety data...</p>
      </div>
    );
  }

  const fileName = `Safety_Report_${format(new Date(), "yyyy-MM-dd")}.pdf`;

  return (
    <div className="h-screen flex flex-col bg-muted/20">
      <div className="bg-white border-b px-4 py-3 flex items-center justify-between shrink-0">
        <div>
          <h1 className="font-bold text-lg">Print Preview</h1>
          <p className="text-sm text-muted-foreground">Safety & Compliance Report</p>
        </div>
        <button
          className="inline-flex items-center gap-2 bg-primary text-primary-foreground px-4 py-2 rounded-md text-sm font-medium hover:bg-primary/90 transition-colors"
          onClick={async () => {
            const blob = await pdf(
              <PDFDocument
                submissions={submissions}
                companyName={companyName}
                sections={sections}
              />
            ).toBlob();
            const url = URL.createObjectURL(blob);
            const a = document.createElement("a");
            a.href = url;
            a.download = fileName;
            document.body.appendChild(a);
            a.click();
            document.body.removeChild(a);
            URL.revokeObjectURL(url);

            const { mirrorToLocalDrive } = await import("@/lib/driveSyncPipeline");
            await mirrorToLocalDrive(fileName, blob);
          }}
        >
          Download PDF
        </button>
      </div>
      <div className="flex-1">
        <PDFViewer width="100%" height="100%" className="border-0">
          <PDFDocument
            submissions={submissions}
            companyName={companyName}
            sections={sections}
          />
        </PDFViewer>
      </div>
    </div>
  );
}
