import { useSearch } from "wouter";
import {
  Document,
  Page,
  Text,
  View,
  PDFViewer,
  PDFDownloadLink,
} from "@react-pdf/renderer";
import {
  customFetch,
  useGetMe,
} from "@workspace/api-client-react";
import type { FormSubmissionRecord, FormTemplateRecord } from "@workspace/api-client-react";
import { useQuery } from "@tanstack/react-query";
import { format } from "date-fns";

import { styles, COLORS } from "@/components/pdf/theme";
import SafetySubmissionsSection from "@/components/pdf/SafetySubmissionsSection";

function PDFHeader({ companyName }: { companyName: string }) {
  return (
    <View style={styles.header} fixed>
      <Text style={styles.headerTitle}>Site Snap</Text>
      <Text style={styles.headerSubtitle}>
        Safety & Compliance Report{companyName ? ` \u2014 ${companyName}` : ""}
      </Text>
    </View>
  );
}

function PDFFooter() {
  return (
    <View style={styles.footer} fixed>
      <Text>Generated by Site Snap on {format(new Date(), "MMM d, yyyy")}</Text>
      <Text
        render={({ pageNumber, totalPages }) => `Page ${pageNumber} of ${totalPages}`}
      />
    </View>
  );
}

interface SafetyNotesSectionProps {
  submissions: FormSubmissionRecord[];
}

function SafetyNotesSection({ submissions }: SafetyNotesSectionProps) {
  const withNotes = submissions.filter((s) => s.aiSummary);

  if (withNotes.length === 0) {
    return (
      <View>
        <Text style={styles.sectionTitle}>Safety Notes & AI Summaries</Text>
        <View style={styles.sectionDivider} />
        <Text style={styles.emptyState}>No AI summaries or safety notes available.</Text>
      </View>
    );
  }

  return (
    <View>
      <Text style={styles.sectionTitle}>Safety Notes & AI Summaries</Text>
      <View style={styles.sectionDivider} />
      {withNotes.map((sub) => (
        <View key={sub.id} style={styles.card}>
          <Text style={styles.cardTitle}>{sub.templateName ?? "Safety Form"}</Text>
          <Text style={styles.smallText}>
            {format(new Date(sub.createdAt), "MMM d, yyyy")}
            {sub.workerName ? ` \u2014 ${sub.workerName}` : ""}
          </Text>
          <View style={{ marginTop: 6, backgroundColor: "#f0f9ff", padding: 6, borderRadius: 3 }}>
            <Text style={[styles.smallText, { color: COLORS.blue }]}>{sub.aiSummary}</Text>
          </View>
        </View>
      ))}
    </View>
  );
}

function TemplatesSection({ templates }: { templates: FormTemplateRecord[] }) {
  if (!templates || templates.length === 0) {
    return (
      <View>
        <Text style={styles.sectionTitle}>Available Form Templates</Text>
        <View style={styles.sectionDivider} />
        <Text style={styles.emptyState}>No form templates configured.</Text>
      </View>
    );
  }

  return (
    <View>
      <Text style={styles.sectionTitle}>Available Form Templates</Text>
      <View style={styles.sectionDivider} />
      {templates.map((t) => (
        <View key={t.id} style={[styles.card, { flexDirection: "row", justifyContent: "space-between" }]}>
          <View>
            <Text style={styles.cardTitle}>{t.name}</Text>
            <Text style={styles.smallText}>Category: {t.category}</Text>
          </View>
          <Text
            style={[
              styles.badge,
              {
                backgroundColor: t.isActive ? `${COLORS.green}15` : `${COLORS.mutedText}15`,
                color: t.isActive ? COLORS.green : COLORS.mutedText,
              },
            ]}
          >
            {t.isActive ? "Active" : "Inactive"}
          </Text>
        </View>
      ))}
    </View>
  );
}

interface PDFDocumentProps {
  submissions: FormSubmissionRecord[];
  templates: FormTemplateRecord[];
  companyName: string;
  sections: Record<string, boolean>;
}

function PDFDocument({ submissions, templates, companyName, sections }: PDFDocumentProps) {
  return (
    <Document>
      {/* Overview / Stats */}
      <Page size="A4" style={styles.page}>
        <PDFHeader companyName={companyName} />
        <View>
          <Text style={styles.sectionTitle}>Overview</Text>
          <View style={styles.sectionDivider} />
          <View style={styles.grid2}>
            {[
              { label: "Total Submissions", value: String(submissions.length) },
              { label: "Inspections", value: String(submissions.filter((s) => s.templateCategory === "safety").length) },
              { label: "Hazard Reports", value: String(submissions.filter((s) => s.templateCategory === "hazard").length) },
              { label: "Incidents", value: String(submissions.filter((s) => s.templateCategory === "injury").length) },
              { label: "Toolbox Talks", value: String(submissions.filter((s) => s.templateCategory === "toolbox").length) },
              { label: "Form Templates", value: String(templates.length) },
            ].map(({ label, value }) => (
              <View key={label} style={[styles.gridItem, styles.card]}>
                <Text style={styles.label}>{label}</Text>
                <Text style={[styles.value, { fontSize: 16, marginTop: 4 }]}>{value}</Text>
              </View>
            ))}
          </View>
        </View>
        <PDFFooter />
      </Page>

      {/* Inspections */}
      {sections.inspections && (
        <Page size="A4" style={styles.page}>
          <PDFHeader companyName={companyName} />
          <SafetySubmissionsSection submissions={submissions} category="safety" title="Inspections" />
          <PDFFooter />
        </Page>
      )}

      {/* Hazard Log */}
      {sections.hazard && (
        <Page size="A4" style={styles.page}>
          <PDFHeader companyName={companyName} />
          <SafetySubmissionsSection submissions={submissions} category="hazard" title="Hazard Log" />
          <PDFFooter />
        </Page>
      )}

      {/* Incident Reports */}
      {sections.incidents && (
        <Page size="A4" style={styles.page}>
          <PDFHeader companyName={companyName} />
          <SafetySubmissionsSection submissions={submissions} category="injury" title="Incident Reports" />
          <PDFFooter />
        </Page>
      )}

      {/* Toolbox Talks */}
      {sections.toolbox && (
        <Page size="A4" style={styles.page}>
          <PDFHeader companyName={companyName} />
          <SafetySubmissionsSection submissions={submissions} category="toolbox" title="Toolbox Talks" />
          <PDFFooter />
        </Page>
      )}

      {/* PPE Compliance (uses safety category with PPE-specific title) */}
      {sections.ppe && (
        <Page size="A4" style={styles.page}>
          <PDFHeader companyName={companyName} />
          <SafetySubmissionsSection submissions={submissions} category="safety" title="PPE Compliance" />
          <PDFFooter />
        </Page>
      )}

      {/* Safety Notes / AI Summaries */}
      {sections.notes && (
        <Page size="A4" style={styles.page}>
          <PDFHeader companyName={companyName} />
          <SafetyNotesSection submissions={submissions} />
          <PDFFooter />
        </Page>
      )}

      {/* Templates */}
      {sections.templates && (
        <Page size="A4" style={styles.page}>
          <PDFHeader companyName={companyName} />
          <TemplatesSection templates={templates} />
          <PDFFooter />
        </Page>
      )}
    </Document>
  );
}

export default function SafetyPrintPage() {
  const search = useSearch();
  const paramsObj = new URLSearchParams(search);

  const sections: Record<string, boolean> = {
    inspections: paramsObj.get("inspections") === "true",
    hazard: paramsObj.get("hazard") === "true",
    incidents: paramsObj.get("incidents") === "true",
    toolbox: paramsObj.get("toolbox") === "true",
    ppe: paramsObj.get("ppe") === "true",
    notes: paramsObj.get("notes") === "true",
    templates: paramsObj.get("templates") === "true",
  };

  const { data: me } = useGetMe();
  const companyName = me?.company?.name ?? "";

  const { data: submissions = [], isLoading: subsLoading } = useQuery<FormSubmissionRecord[]>({
    queryKey: ["safety-submissions-print"],
    queryFn: () => customFetch(`/api/safety/submissions`),
  });

  const { data: templates = [], isLoading: tplLoading } = useQuery<FormTemplateRecord[]>({
    queryKey: ["safety-templates-print"],
    queryFn: () => customFetch(`/api/safety/templates`),
  });

  if (subsLoading || tplLoading) {
    return (
      <div className="flex items-center justify-center h-screen">
        <p className="text-muted-foreground">Loading safety data...</p>
      </div>
    );
  }

  const fileName = `Safety_Report_${format(new Date(), "yyyy-MM-dd")}.pdf`;

  return (
    <div className="h-screen flex flex-col bg-muted/20">
      <div className="bg-white border-b px-4 py-3 flex items-center justify-between shrink-0">
        <div>
          <h1 className="font-bold text-lg">Print Preview</h1>
          <p className="text-sm text-muted-foreground">Safety & Compliance Report</p>
        </div>
        <PDFDownloadLink
          document={
            <PDFDocument
              submissions={submissions}
              templates={templates}
              companyName={companyName}
              sections={sections}
            />
          }
          fileName={fileName}
          className="inline-flex items-center gap-2 bg-primary text-primary-foreground px-4 py-2 rounded-md text-sm font-medium hover:bg-primary/90 transition-colors"
        >
          {({ loading }) => (loading ? "Generating PDF..." : "Download PDF")}
        </PDFDownloadLink>
      </div>
      <div className="flex-1">
        <PDFViewer width="100%" height="100%" className="border-0">
          <PDFDocument
            submissions={submissions}
            templates={templates}
            companyName={companyName}
            sections={sections}
          />
        </PDFViewer>
      </div>
    </div>
  );
}
